name: "Example 8: Catch invalid environment files"

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "develop"
      - "main"
      - "master"
  schedule:
    # Note that cronjobs run on master/main by default
    - cron: "0 0 * * *"

jobs:
  example-8:
    # prevent cronjobs from running on forks
    if:
      (github.event_name == 'schedule' && github.repository ==
      'conda-incubator/setup-miniconda') || (github.event_name != 'schedule')
    name: Ex8 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.8", "3.11"]
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: setup-miniconda
        continue-on-error: true
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          environment-file: etc/example-faulty-environment.yml
      - name: Check previous step failed
        shell: bash
        if: always()
        run: ${{ steps.setup-miniconda.outcome == 'failure' }}
