name: "Example 15: Linux ARM"

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "develop"
      - "main"
      - "master"
  schedule:
    # Note that cronjobs run on master/main by default
    - cron: "0 0 * * *"

jobs:
  example-15:
    # prevent cronjobs from running on forks
    if:
      (github.event_name == 'schedule' && github.repository ==
      'conda-incubator/setup-miniconda') || (github.event_name != 'schedule')
    name: Ex15 (os=${{ matrix.os }} variant=${{ matrix.variant }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-24.04-arm"]
        variant: ["Miniforge3", "Miniconda", "no-variant", "empty-with"]
    steps:
      - uses: actions/checkout@v5
      - uses: ./
        if: matrix.variant == 'Miniforge3'
        id: setup-miniforge
        continue-on-error: true
        with:
          auto-update-conda: true
          miniforge-variant: ${{ matrix.variant }}
          miniforge-version: latest
      - uses: ./
        if: matrix.variant == 'Miniconda'
        id: setup-miniconda
        continue-on-error: true
        with:
          auto-update-conda: true
          miniconda-version: latest
      - uses: ./
        if: matrix.variant == 'no-variant'
        id: setup-miniforge-no-variant
        continue-on-error: true
        with:
          miniforge-version: latest
      - uses: ./
        if: matrix.variant == 'empty-with'
        id: setup-miniconda-empty-with
        continue-on-error: true
      - name: Conda info
        shell: bash -el {0}
        run: conda info
      - name: Conda list
        shell: bash -el {0}
        run: conda list
      - name: Environment
        shell: bash -el {0}
        run: printenv | sort
      - name: Create an environment
        shell: bash -el {0}
        run: conda create -n unused --dry-run zlib
      - name: Run mamba
        if: matrix.variant == 'Miniforge3'
        shell: bash -el {0}
        run: mamba --version
      - name: Install Python
        shell: bash -el {0}
        run: conda install -y python
      - name: Check architecture
        shell: bash -el {0}
        run: |
          python -c "import platform; assert platform.machine() == 'aarch64', platform.machine()"
