name: "Zizmor"

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "develop"
      - "main"
      - "master"

concurrency:
  group:
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions: {}

jobs:
  zizmor:
    name: Analyze workflows
    runs-on: "ubuntu-latest"
    timeout-minutes: 10
    permissions:
      contents: read
      security-events: write # upload SARIF results to code scanning
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: zizmorcore/zizmor-action@5f14fd08f7cf1cb1609c1e344975f152c7ee938d # v0.5.6
